Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/11/2022
Var
// Seção de Declarações das variáveis 
x:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para x de 1 ate 150 faca
     escreval(x)
     fimpara

Fimalgoritmo